import { TrainingExample } from './types';

export const TRAINING_DATASET: TrainingExample[] = [
  // ==========================================
  // --- FOOD (75 examples) ---
  // ==========================================
  { text: "pizza delivery for dinner with roommates", category: "Food" },
  { text: "lunch at college canteen with friends", category: "Food" },
  { text: "groceries from supermarket vegetables and milk", category: "Food" },
  { text: "hot coffee and croissant at cafe", category: "Food" },
  { text: "breakfast masala dosa and filter coffee", category: "Food" },
  { text: "zomato online food order biryani", category: "Food" },
  { text: "swiggy dinner order burger and fries", category: "Food" },
  { text: "dominos cheese burst pizza and garlic bread", category: "Food" },
  { text: "mcdonalds meal with coke and burger", category: "Food" },
  { text: "subway sandwich and iced tea combo", category: "Food" },
  { text: "weekly vegetable and fruit shopping from mandi", category: "Food" },
  { text: "dinner buffet at barbecue restaurant", category: "Food" },
  { text: "evening tea snacks samosa and chai", category: "Food" },
  { text: "bakery pastries birthday cake and cookies", category: "Food" },
  { text: "ice cream sundae parlour treat", category: "Food" },
  { text: "kfc fried chicken bucket and dips", category: "Food" },
  { text: "chinese noodles fried rice and momos", category: "Food" },
  { text: "shawarma and fresh fruit juice", category: "Food" },
  { text: "milk bread butter curd eggs purchase", category: "Food" },
  { text: "starbucks cappuccino and blueberry muffin", category: "Food" },
  { text: "organic food store pulses rice and spices", category: "Food" },
  { text: "street food pani puri chat and bhel", category: "Food" },
  { text: "office cafeteria lunch thali", category: "Food" },
  { text: "sweet shop mithai gulab jamun and rasgulla", category: "Food" },
  { text: "midnight snack delivery chips and cold drinks", category: "Food" },
  { text: "bistro pasta garlic bread and tiramisu", category: "Food" },
  { text: "meat fish and chicken from butcher", category: "Food" },
  { text: "protein shake and healthy granola bar", category: "Food" },
  { text: "zepto instant grocery order snacks and drinks", category: "Food" },
  { text: "blinkit quick delivery milk eggs and bread", category: "Food" },
  { text: "tiffin service monthly lunch subscription", category: "Food" },
  { text: "family dinner at south indian restaurant", category: "Food" },
  { text: "waffles with chocolate syrup and whipped cream", category: "Food" },
  { text: "tea stall cutting chai and biscuit", category: "Food" },
  { text: "dinner takeaway chicken tikka and butter naan", category: "Food" },
  { text: "packaged drinking water bottle crate", category: "Food" },
  { text: "fast food wraps and french fries combo", category: "Food" },
  { text: "lunch box meal pack from mess", category: "Food" },
  { text: "sushi and dim sums dinner meal", category: "Food" },
  { text: "frozen snacks nuggets and potato patties", category: "Food" },
  { text: "cold pressed juice cleanse bottle", category: "Food" },
  { text: "barbeque nation dinner buffet coupon", category: "Food" },
  { text: "haldirams thali and sweets purchase", category: "Food" },
  { text: "baskin robbins waffle cone chocolate scoop", category: "Food" },
  { text: "chole bhature and lassi breakfast", category: "Food" },
  { text: "poha jalebi morning breakfast treat", category: "Food" },
  { text: "chai point ginger tea and bun maska", category: "Food" },
  { text: "pizza hut pan pizza meal for two", category: "Food" },
  { text: "burger king whopper meal and peri peri fries", category: "Food" },
  { text: "tandoori momos and spring roll street stall", category: "Food" },
  { text: "dry fruits almonds walnuts cashew box", category: "Food" },
  { text: "instamart grocery delivery cooking oil and atta", category: "Food" },
  { text: "bigbasket monthly grocery staples order", category: "Food" },
  { text: "nature basket imported cheese and olive oil", category: "Food" },
  { text: "dunkin donuts glazed box and latte", category: "Food" },
  { text: "roll and kebab roll food truck snack", category: "Food" },
  { text: "roasted chicken salad and soup healthy dinner", category: "Food" },
  { text: "fresh tender coconut water roadside stall", category: "Food" },
  { text: "vada pav and misal pav snack", category: "Food" },
  { text: "dabba tiffin food delivery hostel mess", category: "Food" },
  { text: "ice cream tub amul real milk vanilla", category: "Food" },
  { text: "roasted makhanas and diet namkeen snacks", category: "Food" },
  { text: "south indian idli vada sambar combo", category: "Food" },
  { text: "ramen bowl noodles and tofu broth", category: "Food" },
  { text: "mexican tacos and nachos cheese dip", category: "Food" },
  { text: "bakery sourdough loaf and cheddar cheese", category: "Food" },
  { text: "tea time rusks and marie biscuits pack", category: "Food" },
  { text: "hyderabadi dum biryani handi takeaway", category: "Food" },
  { text: "college campus maggi stall noodles snack", category: "Food" },
  { text: "falooda kulfi and rabdi dessert treat", category: "Food" },
  { text: "peanut butter and whole wheat brown bread", category: "Food" },
  { text: "whey protein isolate tub supplement powder", category: "Food" },
  { text: "honey and organic green tea bags", category: "Food" },
  { text: "fruit salad bowl with watermelon and papaya", category: "Food" },
  { text: "pancake stack maple syrup breakfast brunch", category: "Food" },

  // ==========================================
  // --- TRANSPORT (75 examples) ---
  // ==========================================
  { text: "uber cab ride to college campus", category: "Transport" },
  { text: "ola cab booking to railway station", category: "Transport" },
  { text: "petrol refill at indian oil petrol pump", category: "Transport" },
  { text: "diesel fuel for car long drive", category: "Transport" },
  { text: "auto rickshaw fare to metro station", category: "Transport" },
  { text: "monthly metro smart card recharge", category: "Transport" },
  { text: "local city bus ticket commute", category: "Transport" },
  { text: "train ticket reservation irctc tatkal", category: "Transport" },
  { text: "flight tickets booking indigo airlines", category: "Transport" },
  { text: "rapido bike taxi quick ride to office", category: "Transport" },
  { text: "highway toll plaza fastag recharge", category: "Transport" },
  { text: "car parking ticket at shopping mall", category: "Transport" },
  { text: "two wheeler scooter servicing and engine oil", category: "Transport" },
  { text: "puncture repair tyre tube and air pressure", category: "Transport" },
  { text: "intercity bus ticket redbus booking", category: "Transport" },
  { text: "car wash interior cleaning and polishing", category: "Transport" },
  { text: "bicycle chain repair and tune up", category: "Transport" },
  { text: "airport cab drop prepaid taxi counter", category: "Transport" },
  { text: "monthly suburban train pass travel", category: "Transport" },
  { text: "ferry boat ticket river crossing", category: "Transport" },
  { text: "motorcycle helmet and riding gloves", category: "Transport" },
  { text: "ev scooter charging station battery recharge", category: "Transport" },
  { text: "vehicle insurance renewal third party liability", category: "Transport" },
  { text: "traffic challan fine payment transport portal", category: "Transport" },
  { text: "rental car self drive booking zoomcar", category: "Transport" },
  { text: "cab surge price late night drop home", category: "Transport" },
  { text: "shared van shuttle transit fare", category: "Transport" },
  { text: "college bus transport fee semester", category: "Transport" },
  { text: "gasoline fuel topup bpcl station", category: "Transport" },
  { text: "battery replacement for four wheeler car", category: "Transport" },
  { text: "uber auto ride to market", category: "Transport" },
  { text: "toll tax payment express highway", category: "Transport" },
  { text: "motorcycle engine oil change castrol", category: "Transport" },
  { text: "subway train metro token ticket fare", category: "Transport" },
  { text: "car windshield wiper replacement", category: "Transport" },
  { text: "bullet motorcycle disc brake pad replacement", category: "Transport" },
  { text: "uber ride back home after presentation", category: "Transport" },
  { text: "interstate bus travel sleeper ticket booking", category: "Transport" },
  { text: "cab fare to international terminal airport", category: "Transport" },
  { text: "car jump start and road assistance towing", category: "Transport" },
  { text: "cng gas cylinder fillup station", category: "Transport" },
  { text: "air india domestic round trip flight", category: "Transport" },
  { text: "irctc premium tatkal train ticket ac tier", category: "Transport" },
  { text: "valet parking fee at restaurant", category: "Transport" },
  { text: "scooter tyre replacement mrf zapper", category: "Transport" },
  { text: "two wheeler pollution check puc certificate", category: "Transport" },
  { text: "uber shuttle monthly office bus pass", category: "Transport" },
  { text: "ola electric scooter servicing maintenance", category: "Transport" },
  { text: "car wheel alignment and balancing balance", category: "Transport" },
  { text: "highway express toll paytm fastag auto topup", category: "Transport" },
  { text: "rapido auto booking to metro terminal", category: "Transport" },
  { text: "city auto meter fare cash payment", category: "Transport" },
  { text: "speed boat jetty ticket travel", category: "Transport" },
  { text: "railway luggage cloak room charges", category: "Transport" },
  { text: "bike chain lube spray and cleaner kit", category: "Transport" },
  { text: "car coolant refill and radiator flush", category: "Transport" },
  { text: "motorcycle rear view mirror replacement", category: "Transport" },
  { text: "flight seat selection and baggage allowance fee", category: "Transport" },
  { text: "multilevel car parking token fee", category: "Transport" },
  { text: "scooter petrol tank full hpcl petrol bunk", category: "Transport" },
  { text: "vande bharat express chair car ticket irctc", category: "Transport" },
  { text: "uber go hatchback cab ride to clinic", category: "Transport" },
  { text: "drivezy bike rental weekend rental", category: "Transport" },
  { text: "cycle pump air nozzle repair mechanic", category: "Transport" },
  { text: "metro feeder electric bus ticket fare", category: "Transport" },
  { text: "car headlight bulb replacement halogens", category: "Transport" },
  { text: "scooter brake cable wire fix mechanic", category: "Transport" },
  { text: "airport shuttle bus express express fare", category: "Transport" },
  { text: "toll booth cash receipt state highway", category: "Transport" },
  { text: "uber premier sedan ride client meeting", category: "Transport" },
  { text: "car denting painting scratch repair garage", category: "Transport" },
  { text: "synthetic motor oil mobil super quart", category: "Transport" },
  { text: "night taxi ride home from railway terminal", category: "Transport" },
  { text: "monthly parking bay spot rent in society", category: "Transport" },
  { text: "scooter spark plug replacement spark", category: "Transport" },

  // ==========================================
  // --- SHOPPING (75 examples) ---
  // ==========================================
  { text: "bought new running shoes from nike store", category: "Shopping" },
  { text: "clothes shopping at zara shirts and trousers", category: "Shopping" },
  { text: "wireless bluetooth headphones from amazon", category: "Shopping" },
  { text: "casual denim jeans and graphic t-shirt", category: "Shopping" },
  { text: "online shopping flipkart big billion days order", category: "Shopping" },
  { text: "myntra fashion sale dress and sneakers", category: "Shopping" },
  { text: "sunglasses and watch from titan store", category: "Shopping" },
  { text: "leather wallet and belt formal wear", category: "Shopping" },
  { text: "winter jacket hoodie and sweater", category: "Shopping" },
  { text: "laptop bag and travel backpack safari", category: "Shopping" },
  { text: "cosmetics makeup lipstick and sunscreen", category: "Shopping" },
  { text: "perfume cologne and body spray fragrance", category: "Shopping" },
  { text: "bedsheet blanket and pillow cover set", category: "Shopping" },
  { text: "formal shoes oxford leather for interview", category: "Shopping" },
  { text: "eyeglass frames and blue light glasses lenskart", category: "Shopping" },
  { text: "kitchen cookware nonstick frying pan", category: "Shopping" },
  { text: "smartphone case cover and tempered glass screen", category: "Shopping" },
  { text: "fitness tracker smart watch band noise", category: "Shopping" },
  { text: "h&m cotton shirts and chinos trousers", category: "Shopping" },
  { text: "sneakers puma sports gym trainers", category: "Shopping" },
  { text: "desk lamp led study lighting reading light", category: "Shopping" },
  { text: "handbag purse women tote sling bag", category: "Shopping" },
  { text: "skincare face wash serum and moisturizer", category: "Shopping" },
  { text: "meesho online clothes shopping kurtis", category: "Shopping" },
  { text: "umbrella and raincoat monsoon wear", category: "Shopping" },
  { text: "usb c cable and 65w fast charger adapter", category: "Shopping" },
  { text: "scented candles and room freshener spray", category: "Shopping" },
  { text: "sports football and badminton shuttlecocks", category: "Shopping" },
  { text: "cotton socks pack and innerwear garments", category: "Shopping" },
  { text: "jewellery earrings and pendant gift shopping", category: "Shopping" },
  { text: "ajio fashion lifestyle clothing sale haul", category: "Shopping" },
  { text: "trolley suitcase luggage bag american tourister", category: "Shopping" },
  { text: "wireless mouse and mechanical keyboard keycaps", category: "Shopping" },
  { text: "hair trimmer and shaving grooming kit philips", category: "Shopping" },
  { text: "thermal innerwear warmers for winter trip", category: "Shopping" },
  { text: "coffee mug ceramic thermos tumbler sipper", category: "Shopping" },
  { text: "home decor wall art canvas frames posters", category: "Shopping" },
  { text: "footwear slippers flip flops crocs clogs", category: "Shopping" },
  { text: "nykaa cosmetics eyeliner foundation kajal", category: "Shopping" },
  { text: "bath towel and soft bathrobes set", category: "Shopping" },
  { text: "ethnic kurta pajama set diwali festive wear", category: "Shopping" },
  { text: "blazer coat suit jacket raymond fabric", category: "Shopping" },
  { text: "power bank 20000mah portable battery mi", category: "Shopping" },
  { text: "yoga mat non slip fitness exercise mat", category: "Shopping" },
  { text: "running shorts and dry fit sports jersey", category: "Shopping" },
  { text: "crockery ceramic dinner plates and bowls set", category: "Shopping" },
  { text: "curtains and window blinds home furnish", category: "Shopping" },
  { text: "water bottle stainless steel insulated flask", category: "Shopping" },
  { text: "laptop stand aluminum ergonomic riser", category: "Shopping" },
  { text: "shoe rack plastic organizer wardrobe storage", category: "Shopping" },
  { text: "designer wristwatch analog quartz fossil", category: "Shopping" },
  { text: "leather jacket biker coat winter apparel", category: "Shopping" },
  { text: "shampoo conditioner and hair oil loreal", category: "Shopping" },
  { text: "body lotion moisturising cream nivea tub", category: "Shopping" },
  { text: "track pants sweatpants gym jogging trousers", category: "Shopping" },
  { text: "bluetooth speaker portable waterproof boat", category: "Shopping" },
  { text: "wall clock decorative analog clock titan", category: "Shopping" },
  { text: "gym gym duffle bag training workout sack", category: "Shopping" },
  { text: "cotton handkerchiefs and bandanas pack", category: "Shopping" },
  { text: "formal silk tie and cufflinks gift set", category: "Shopping" },
  { text: "casual slip on loafer shoes bata", category: "Shopping" },
  { text: "wooden clothes hangers pack for wardrobe", category: "Shopping" },
  { text: "plant pots ceramic indoor desk succulents", category: "Shopping" },
  { text: "electric iron dry press havells", category: "Shopping" },
  { text: "bed mattress topper and memory foam pillow", category: "Shopping" },
  { text: "casual polo collar t-shirt us polo assn", category: "Shopping" },
  { text: "rain shoes waterproof gumboots", category: "Shopping" },
  { text: "gaming mouse pad extended desk mat xxl", category: "Shopping" },
  { text: "hair styling wax pomade and clay", category: "Shopping" },
  { text: "air purifier filter replacement hepa cartridge", category: "Shopping" },
  { text: "sports water hydration pack running belt", category: "Shopping" },
  { text: "cutlery stainless steel spoons forks set", category: "Shopping" },
  { text: "wardrobe fragrance pouch lavender scent", category: "Shopping" },
  { text: "casual canvas shoes converse all star sneakers", category: "Shopping" },
  { text: "hand luggage cabin duffel bag wildcraft", category: "Shopping" },

  // ==========================================
  // --- BILLS (75 examples) ---
  // ==========================================
  { text: "electricity bill payment discom online", category: "Bills" },
  { text: "broadband wifi internet monthly bill airtel", category: "Bills" },
  { text: "mobile postpaid phone recharge bill jio", category: "Bills" },
  { text: "piped natural gas png cooking gas bill", category: "Bills" },
  { text: "water supply utility municipal bill payment", category: "Bills" },
  { text: "apartment maintenance dues monthly society", category: "Bills" },
  { text: "house rent monthly landlord bank transfer", category: "Bills" },
  { text: "lpg cooking gas cylinder refill indane booking", category: "Bills" },
  { text: "credit card minimum balance statement payment", category: "Bills" },
  { text: "dth cable television recharge tata play", category: "Bills" },
  { text: "property tax municipal corporation online", category: "Bills" },
  { text: "garbage collection and sanitation waste fee", category: "Bills" },
  { text: "mobile prepaid data recharge pack vodafone", category: "Bills" },
  { text: "home loan emi installment auto debit hdfc", category: "Bills" },
  { text: "car loan monthly emi installment payment", category: "Bills" },
  { text: "personal loan emi deduction sbi bank", category: "Bills" },
  { text: "optical fiber fiber net broadband act internet", category: "Bills" },
  { text: "power utility electricity meter tariff unit charge", category: "Bills" },
  { text: "society club house maintenance charges", category: "Bills" },
  { text: "bharat gas lpg cylinder home delivery booking", category: "Bills" },
  { text: "airtel dth television set top box recharge", category: "Bills" },
  { text: "bsnl landline telephone telephone bill payment", category: "Bills" },
  { text: "solar rooftop power connection grid bill", category: "Bills" },
  { text: "society water tanker sharing contribution", category: "Bills" },
  { text: "inverter battery maintenance and water refill", category: "Bills" },
  { text: "dish tv monthly subscription recharge", category: "Bills" },
  { text: "jio fiber high speed internet 100mbps plan", category: "Bills" },
  { text: "bescom electricity quarterly consumption bill", category: "Bills" },
  { text: "torent power electricity bill payment", category: "Bills" },
  { text: "tneb electricity bi-monthly tariff charges", category: "Bills" },
  { text: "adani electricity bill online portal payment", category: "Bills" },
  { text: "mahavitaran electricity power supply payment", category: "Bills" },
  { text: "water tanker supply emergency order for home", category: "Bills" },
  { text: "landlord advance rent security deposit top up", category: "Bills" },
  { text: "society diesel generator power backup fuel charges", category: "Bills" },
  { text: "security guard salary contribution rwa apartment", category: "Bills" },
  { text: "quarterly house water tax municipal jal board", category: "Bills" },
  { text: "hp gas domestic cylinder refill payment online", category: "Bills" },
  { text: "commercial electricity supply submeter bill", category: "Bills" },
  { text: "credit card outstanding balance settled in full", category: "Bills" },
  { text: "airtel extreme fiber broadband 200mbps bill", category: "Bills" },
  { text: "postpaid mobile corporate family plan bill", category: "Bills" },
  { text: "delhi jal board water bill consumer number", category: "Bills" },
  { text: "tata power solar rooftop net metering bill", category: "Bills" },
  { text: "society sinking fund and repair fund levy", category: "Bills" },
  { text: "elevator lift maintenance amc contract share", category: "Bills" },
  { text: "cctv surveillance camera monthly maintenance fee", category: "Bills" },
  { text: "icici bank credit card bill online netbanking", category: "Bills" },
  { text: "axis bank credit card payment cred app", category: "Bills" },
  { text: "two wheeler loan emi auto debit deduction", category: "Bills" },
  { text: "education loan emi interest monthly payment", category: "Bills" },
  { text: "consumer loan tv appliance no cost emi", category: "Bills" },
  { text: "sun direct dth channel pack recharge", category: "Bills" },
  { text: "airtel prepaid unlimited 84 days calling plan", category: "Bills" },
  { text: "jio 5g true welcome pack data voucher addon", category: "Bills" },
  { text: "vi vodafone idea postpaid monthly billing invoice", category: "Bills" },
  { text: "sewage and drainage cess municipal tax", category: "Bills" },
  { text: "fire safety equipment inspection fee in society", category: "Bills" },
  { text: "residential building intercom repair service charge", category: "Bills" },
  { text: "ro water purifier annual maintenance contract amc", category: "Bills" },
  { text: "air conditioner amc annual servicing maintenance", category: "Bills" },
  { text: "chimney and hob annual service fee urban company", category: "Bills" },
  { text: "gas geyser pipeline checkup and inspection charge", category: "Bills" },
  { text: "land registry municipal conversion tax bill", category: "Bills" },
  { text: "commercial shop rent monthly lease payment", category: "Bills" },
  { text: "warehouse godown monthly rental bill", category: "Bills" },
  { text: "student pg paying guest accommodation monthly rent", category: "Bills" },
  { text: "hostel room rent and electricity surcharge", category: "Bills" },
  { text: "shared flat broker commission rental bill", category: "Bills" },
  { text: "society late payment surcharge fine utility", category: "Bills" },
  { text: "swimming pool and gym amenity maintenance fee", category: "Bills" },
  { text: "broadband speed boost add-on data top-up", category: "Bills" },
  { text: "landline broadband bundle combo bill bsnl", category: "Bills" },
  { text: "gas pipeline connection meter inspection charges", category: "Bills" },
  { text: "street lighting community contribution rwa", category: "Bills" },

  // ==========================================
  // --- ENTERTAINMENT (75 examples) ---
  // ==========================================
  { text: "movie ticket pvr cinemas popcorn combo", category: "Entertainment" },
  { text: "netflix premium 4k monthly subscription", category: "Entertainment" },
  { text: "spotify individual premium music streaming", category: "Entertainment" },
  { text: "bookmyshow movie tickets booking inox", category: "Entertainment" },
  { text: "amazon prime video yearly subscription renewal", category: "Entertainment" },
  { text: "youtube premium family ad-free membership", category: "Entertainment" },
  { text: "disney plus hotstar annual vip plan", category: "Entertainment" },
  { text: "gaming arcade smash bowling and laser tag", category: "Entertainment" },
  { text: "video game purchase steam summer sale", category: "Entertainment" },
  { text: "playstation network plus deluxe subscription", category: "Entertainment" },
  { text: "live music concert ticket entry pass", category: "Entertainment" },
  { text: "stand up comedy show ticket zakir khan", category: "Entertainment" },
  { text: "amusement water park entry ticket wonderla", category: "Entertainment" },
  { text: "audible audiobooks monthly credit subscription", category: "Entertainment" },
  { text: "apple music monthly individual subscription", category: "Entertainment" },
  { text: "board game cafe entry and games fee", category: "Entertainment" },
  { text: "escape room mystery game weekend with friends", category: "Entertainment" },
  { text: "cricket match stadium ticket ipl match", category: "Entertainment" },
  { text: "pub weekend drinks brewery craft beer", category: "Entertainment" },
  { text: "club cover charge night party entry fee", category: "Entertainment" },
  { text: "karting go kart racing track ticket", category: "Entertainment" },
  { text: "museum science center exhibition ticket", category: "Entertainment" },
  { text: "art exhibition and painting gallery ticket", category: "Entertainment" },
  { text: "theatre play drama ticket stage show", category: "Entertainment" },
  { text: "comic con passes weekend entry ticket", category: "Entertainment" },
  { text: "nintendo switch digital game download", category: "Entertainment" },
  { text: "xbox game pass ultimate monthly tier", category: "Entertainment" },
  { text: "cinema snacks caramel popcorn and large coke", category: "Entertainment" },
  { text: "karaoke room rental lounge with friends", category: "Entertainment" },
  { text: "snooker pool table hourly gaming fee", category: "Entertainment" },
  { text: "carnival fun fair giant wheel ride ticket", category: "Entertainment" },
  { text: "planetarium sky show 3d dome ticket", category: "Entertainment" },
  { text: "circus show acrobatic performance ticket", category: "Entertainment" },
  { text: "magic show live stage ticket passes", category: "Entertainment" },
  { text: "laser tag arena session battle games", category: "Entertainment" },
  { text: "paintball shooting arena protective gear pass", category: "Entertainment" },
  { text: "disco club lounge dance floor entry pass", category: "Entertainment" },
  { text: "movie tickets cinepolis recliners 3d glasses", category: "Entertainment" },
  { text: "imax 3d movie ticket avatar screening", category: "Entertainment" },
  { text: "twitch streamer channel sub donation", category: "Entertainment" },
  { text: "discord nitro yearly premium subscription", category: "Entertainment" },
  { text: "sony liv annual subscription ott streaming", category: "Entertainment" },
  { text: "zee5 premium regional movies subscription", category: "Entertainment" },
  { text: "jio cinema premium hbo show subscription", category: "Entertainment" },
  { text: "apple tv plus original shows streaming", category: "Entertainment" },
  { text: "gaana plus music app ad free plan", category: "Entertainment" },
  { text: "wynk music caller tune and subscription", category: "Entertainment" },
  { text: "smaaash virtual reality vr roller coaster game", category: "Entertainment" },
  { text: "timezone arcade game card credits balance", category: "Entertainment" },
  { text: "bowling alley shoe rental and game frames", category: "Entertainment" },
  { text: "trampoline park hourly jumping session pass", category: "Entertainment" },
  { text: "ice skating rink entry and skate rentals", category: "Entertainment" },
  { text: "scuba diving ocean discovery session ticket", category: "Entertainment" },
  { text: "zipline and adventure ropes obstacle course", category: "Entertainment" },
  { text: "pottery making workshop weekend fun class", category: "Entertainment" },
  { text: "standup open mic night comedy ticket", category: "Entertainment" },
  { text: "dj music festival sunburn ticket entry wristband", category: "Entertainment" },
  { text: "football turf hourly rental split with friends", category: "Entertainment" },
  { text: "cricket box turf lights hourly slot booking", category: "Entertainment" },
  { text: "badminton court hourly booking fee fitso", category: "Entertainment" },
  { text: "indoor swimming pool guest day pass", category: "Entertainment" },
  { text: "zoo safari and animal sanctuary ticket entry", category: "Entertainment" },
  { text: "botanical flower garden entry ticket fee", category: "Entertainment" },
  { text: "fort historical monument entry ticket heritage", category: "Entertainment" },
  { text: "audio sound system dj hire for celebration", category: "Entertainment" },
  { text: "board game catan expansion board set buy", category: "Entertainment" },
  { text: "deck of playing cards and poker chip tokens", category: "Entertainment" },
  { text: "valorant battle pass points vp buy riot", category: "Entertainment" },
  { text: "bgmi battlegrounds pubg uc skin purchase", category: "Entertainment" },
  { text: "fifa ultimate team points pack purchase", category: "Entertainment" },
  { text: "chess com diamond membership tactics subscription", category: "Entertainment" },
  { text: "craft beer tasting flight microbrewery tour", category: "Entertainment" },
  { text: "drive in cinema screening ticket car pass", category: "Entertainment" },
  { text: "rooftop film festival movie screening ticket", category: "Entertainment" },
  { text: "puppet show cultural folk dance entry passes", category: "Entertainment" },

  // ==========================================
  // --- HEALTHCARE (75 examples) ---
  // ==========================================
  { text: "doctor consultation fee general physician clinic", category: "Healthcare" },
  { text: "prescription medicines pharmacy apollo medicines", category: "Healthcare" },
  { text: "dental tooth cleaning and cavity filling dentist", category: "Healthcare" },
  { text: "blood test lipid profile and cbc diagnostics", category: "Healthcare" },
  { text: "eye clinic consultation and vision power check", category: "Healthcare" },
  { text: "multivitamin tablets and zinc vitamin c capsules", category: "Healthcare" },
  { text: "physiotherapy session back pain spine clinic", category: "Healthcare" },
  { text: "dermatologist skin clinic acne treatment fee", category: "Healthcare" },
  { text: "cough syrup paracetamol and pain relief spray", category: "Healthcare" },
  { text: "bandages antiseptic savlon dettol and cotton roll", category: "Healthcare" },
  { text: "x-ray chest scan and radiologist report", category: "Healthcare" },
  { text: "hospital opd consultation registration charges", category: "Healthcare" },
  { text: "health insurance annual policy premium star health", category: "Healthcare" },
  { text: "pharmeasy online medicine order delivery", category: "Healthcare" },
  { text: "tata 1mg diagnostic health checkup package", category: "Healthcare" },
  { text: "orthopedic joint knee consultation knee doctor", category: "Healthcare" },
  { text: "covid rt pcr antigen test certificate report", category: "Healthcare" },
  { text: "thyroid tsh hormone blood test thyroid care", category: "Healthcare" },
  { text: "blood pressure monitor digital bp machine omron", category: "Healthcare" },
  { text: "glucometer test strips blood sugar monitoring", category: "Healthcare" },
  { text: "thermometer digital fever temperature check", category: "Healthcare" },
  { text: "crepe bandage sprain spray volini pain ointment", category: "Healthcare" },
  { text: "nasal drops allergy saline spray otrivin", category: "Healthcare" },
  { text: "antacid gelusil digene acidity relief syrup", category: "Healthcare" },
  { text: "contact lens solution renu and lens cleaning case", category: "Healthcare" },
  { text: "orthopedic lumbar support belt spine posture", category: "Healthcare" },
  { text: "ayurvedic kadha and immunity booster chavanprash", category: "Healthcare" },
  { text: "homeopathy medicine drops consultation clinic", category: "Healthcare" },
  { text: "root canal treatment rct dental crown cap", category: "Healthcare" },
  { text: "wisdom tooth extraction surgery dental clinic", category: "Healthcare" },
  { text: "ultrasound abdomen sonography scan charges", category: "Healthcare" },
  { text: "mri scan brain spine imaging diagnostic center", category: "Healthcare" },
  { text: "ct scan head trauma imaging charges", category: "Healthcare" },
  { text: "ecg heart test cardiology doctor checkup", category: "Healthcare" },
  { text: "pediatrician baby vaccination immunisation shot", category: "Healthcare" },
  { text: "tetanus injection tt shot emergency clinic", category: "Healthcare" },
  { text: "ambulance service emergency patient transfer", category: "Healthcare" },
  { text: "hospital day care bed admission charges", category: "Healthcare" },
  { text: "vitamin d3 weekly sachet supplement calcefor", category: "Healthcare" },
  { text: "iron and folic acid tablets deficiency cure", category: "Healthcare" },
  { text: "omega 3 fish oil capsules triple strength", category: "Healthcare" },
  { text: "ent ear wax cleaning and hearing audiometry test", category: "Healthcare" },
  { text: "psychologist mental health counseling therapy", category: "Healthcare" },
  { text: "psychiatrist prescription anti anxiety medicine", category: "Healthcare" },
  { text: "gynecologist consultation scan sonography", category: "Healthcare" },
  { text: "prenatal vitamins pregnancy care medicine", category: "Healthcare" },
  { text: "pulse oximeter finger oxygen level monitor", category: "Healthcare" },
  { text: "vaporizer steamer cold inhaler machine", category: "Healthcare" },
  { text: "antibiotics amoxicillin course chemist shop", category: "Healthcare" },
  { text: "allergy cetirizine tablet antihistamine pack", category: "Healthcare" },
  { text: "eye drops lubricating tears refresh tears", category: "Healthcare" },
  { text: "digestive enzymes and probiotic gut bacteria cap", category: "Healthcare" },
  { text: "calcium tablets with magnesium and zinc", category: "Healthcare" },
  { text: "medicated acne facewash benzoyl peroxide gel", category: "Healthcare" },
  { text: "pain killer brufen combiflam tablet strip", category: "Healthcare" },
  { text: "wound dressing and stitches removal dispensary", category: "Healthcare" },
  { text: "physiotherapy knee rehabilitation workout therapist", category: "Healthcare" },
  { text: "neck cervical collar bone support brace", category: "Healthcare" },
  { text: "orthopedic shoes insole arch support insert", category: "Healthcare" },
  { text: "hearing aid battery cells zinc air pack", category: "Healthcare" },
  { text: "asthma inhaler asthalin rotacaps pump", category: "Healthcare" },
  { text: "diabetic foot cream and sugar control herbal tea", category: "Healthcare" },
  { text: "mediclaim hospitalization copay out of pocket", category: "Healthcare" },
  { text: "dr lal pathlabs vitamin b12 test report", category: "Healthcare" },
  { text: "metropolis diagnostics complete urine analysis", category: "Healthcare" },
  { text: "medanta hospital outpatient consultation token", category: "Healthcare" },
  { text: "max healthcare specialist surgery opinion fee", category: "Healthcare" },
  { text: "fortis clinic health wellness screening checkup", category: "Healthcare" },
  { text: "ayush treatment panchakarma body detox therapy", category: "Healthcare" },
  { text: "heat pad electric hot water bag pain relief", category: "Healthcare" },
  { text: "ice pack cold compress gel pad sports injury", category: "Healthcare" },
  { text: "knee compression sleeves knee brace athletic", category: "Healthcare" },
  { text: "antiseptic mouthwash chlorhexidine betadine", category: "Healthcare" },
  { text: "oral rehydration salts ors sachets dehydration", category: "Healthcare" },
  { text: "blood donation testing hemoglobin lab test", category: "Healthcare" },

  // ==========================================
  // --- EDUCATION (75 examples) ---
  // ==========================================
  { text: "college semester tuition fee payment portal", category: "Education" },
  { text: "university examination form registration fee", category: "Education" },
  { text: "engineering textbooks mathematics and physics", category: "Education" },
  { text: "udemy online video course web development bootcamp", category: "Education" },
  { text: "coursera machine learning specialization certificate", category: "Education" },
  { text: "notebooks pens pencils and stationery supplies", category: "Education" },
  { text: "python programming data science masterclass", category: "Education" },
  { text: "gre toefl exam registration ets official fee", category: "Education" },
  { text: "college library annual membership card fee", category: "Education" },
  { text: "campus laboratory practical instruments fee", category: "Education" },
  { text: "ielts academic english proficiency exam fee", category: "Education" },
  { text: "gate entrance exam online application form", category: "Education" },
  { text: "scientific engineering calculator casio fx991", category: "Education" },
  { text: "drawing board mini drafter and engineering graphics", category: "Education" },
  { text: "computer science algorithms dsa course leetcode", category: "Education" },
  { text: "academic research paper ieee journal publishing fee", category: "Education" },
  { text: "coaching institute monthly fees iit jee neet", category: "Education" },
  { text: "cloud practitioner aws certification exam voucher", category: "Education" },
  { text: "project printout binding and xerox spiral photocopy", category: "Education" },
  { text: "school uniform tie badge and shoes purchase", category: "Education" },
  { text: "physics chemistry biology practical record book", category: "Education" },
  { text: "maths formulas handbook and previous question papers", category: "Education" },
  { text: "edx professional certificate micro masters fee", category: "Education" },
  { text: "skillshare annual learning membership discount", category: "Education" },
  { text: "codecademy pro subscription annual renewal", category: "Education" },
  { text: "pluralsight tech tech developer library plan", category: "Education" },
  { text: "foreign language learning duolingo super subscription", category: "Education" },
  { text: "college fest technical symposium registration", category: "Education" },
  { text: "hackathon team registration fee innovation contest", category: "Education" },
  { text: "kindle ebook download deep learning goodfellow", category: "Education" },
  { text: "data structures in c plus plus book korth", category: "Education" },
  { text: "operating system concepts galvin dinosaur book", category: "Education" },
  { text: "computer networks tanenbaum textbook purchase", category: "Education" },
  { text: "highlighter pens sticky notes and flashcards stationery", category: "Education" },
  { text: "whiteboard markers and eraser duster set", category: "Education" },
  { text: "a4 size printer copier paper ream 500 sheets", category: "Education" },
  { text: "geometry box compass scale protector staedtler", category: "Education" },
  { text: "college identity card re-issue penalty charges", category: "Education" },
  { text: "alumni association lifetime enrollment fee", category: "Education" },
  { text: "degree convocation gown rental and certificate fee", category: "Education" },
  { text: "school admission brochure prospectus form", category: "Education" },
  { text: "maths home tuition teacher monthly fee", category: "Education" },
  { text: "english speaking personality development class", category: "Education" },
  { text: "full stack web development mern stack training", category: "Education" },
  { text: "flutter mobile app development training course", category: "Education" },
  { text: "docker kubernetes devops masterclass coupon", category: "Education" },
  { text: "sql database administration oracle certification", category: "Education" },
  { text: "cybersecurity ethical hacking ceh exam voucher", category: "Education" },
  { text: "ai artificial intelligence prompt engineering course", category: "Education" },
  { text: "machine learning math linear algebra coursera", category: "Education" },
  { text: "data analytics powerbi and tableau training course", category: "Education" },
  { text: "digital marketing google ads analytics certification", category: "Education" },
  { text: "graphic design figma ui ux masterclass bootcamp", category: "Education" },
  { text: "cad cam solidworks 3d modeling software training", category: "Education" },
  { text: "embedded systems arduino robotics kit educational", category: "Education" },
  { text: "raspberry pi 4 micro computer student lab kit", category: "Education" },
  { text: "breadboard resistors capacitors electronics kit", category: "Education" },
  { text: "microprocessor 8086 lab kit training session", category: "Education" },
  { text: "thesis hardcopy leather binding golden letter", category: "Education" },
  { text: "plagiarism check turnitin report submission fee", category: "Education" },
  { text: "conference paper presentation registration fee", category: "Education" },
  { text: "springer research book chapter open access fee", category: "Education" },
  { text: "oxford english advanced dictionary reference", category: "Education" },
  { text: "atlas world geography map book orient blackswan", category: "Education" },
  { text: "cat mba entrance exam application cat voucher", category: "Education" },
  { text: "gmat official prep mock test practice test pack", category: "Education" },
  { text: "upsc civil services prelims test series vision ias", category: "Education" },
  { text: "ssc cgl banking exam mock test series testbook", category: "Education" },
  { text: "state psc recruitment test online application", category: "Education" },
  { text: "stenography and typing speed test course fee", category: "Education" },
  { text: "public speaking toastmasters club dues membership", category: "Education" },
  { text: "student study desk wooden chair table study room", category: "Education" },
  { text: "correction pen fluid whitener and camel inks", category: "Education" },
  { text: "stapler machine pin box and paper binder clips", category: "Education" },
  { text: "document file folder display portfolio sheets", category: "Education" },

  // ==========================================
  // --- OTHER (75 examples) ---
  // ==========================================
  { text: "charitable donation to animal rescue shelter ngo", category: "Other" },
  { text: "temple prayer offering pooja flower prasad donation", category: "Other" },
  { text: "notary affidavit lawyer legal stamp paper verification", category: "Other" },
  { text: "passport renewal government seva kendra fee", category: "Other" },
  { text: "bank locker annual rental fee", category: "Other" },
  { text: "dry cleaning and laundry iron wash clothes", category: "Other" },
  { text: "pet food royal canin dog kibble and leash", category: "Other" },
  { text: "pet grooming dog bath and nail trim", category: "Other" },
  { text: "home pest control termite treatment service", category: "Other" },
  { text: "courier speed post shipping parcel charges dhl", category: "Other" },
  { text: "house painter plumbing carpenter home repair labour", category: "Other" },
  { text: "key duplication locksmith charges front door key", category: "Other" },
  { text: "religious festival celebration contribution society fund", category: "Other" },
  { text: "prime minister relief fund flood charity contribution", category: "Other" },
  { text: "wedding gift cash envelope shagun blessing", category: "Other" },
  { text: "luggage porter tip coolie railway station", category: "Other" },
  { text: "credit card late fine and finance charges penalty", category: "Other" },
  { text: "police verification document clearance charges", category: "Other" },
  { text: "loss of wallet cash misplaced miscellaneous", category: "Other" },
  { text: "shoe repair cobbler stitching sole fix", category: "Other" },
  { text: "watch battery change and strap adjustment", category: "Other" },
  { text: "office colleague farewell party gift contribution", category: "Other" },
  { text: "house maid domestic helper monthly salary", category: "Other" },
  { text: "cook monthly remuneration meal preparation", category: "Other" },
  { text: "gardener monthly garden maintenance service", category: "Other" },
  { text: "storage locker monthly facility space rent", category: "Other" },
  { text: "visa application biometric appointment charges", category: "Other" },
  { text: "newspaper monthly delivery subscription hawker", category: "Other" },
  { text: "unforeseen unexpected household expense emergency", category: "Other" },
  { text: "atm transaction fee non-home branch withdrawal", category: "Other" },
  { text: "gift card purchase for colleague anniversary", category: "Other" },
  { text: "birthday gift for friend flowers and bouquet", category: "Other" },
  { text: "donation to orphan children care home", category: "Other" },
  { text: "car key duplicate sensor remote repair", category: "Other" },
  { text: "dry cleaner woolen coat laundry charges", category: "Other" },
  { text: "plumber faucet leakage washer fix labour", category: "Other" },
  { text: "house deep cleaning sanitation service", category: "Other" },
  { text: "cat veterinary vaccination and deworming clinic", category: "Other" },
  { text: "miscellaneous small daily expenses unspecified", category: "Other" },
  { text: "driver bhatta tip overtime cash bonus", category: "Other" },
  { text: "tailor stitching charges suit alterations", category: "Other" },
  { text: "home interior pest fumigation spray cockroach", category: "Other" },
  { text: "bank account minimum balance charge penalty sbi", category: "Other" },
  { text: "cheque book issue and debit card annual fee", category: "Other" },
  { text: "foreign exchange currency conversion markup fee", category: "Other" },
  { text: "apostille legal document attestation service", category: "Other" },
  { text: "court agreement non judicial stamp duty e-stamp", category: "Other" },
  { text: "pet cat litter sand box scoop bentonite clay", category: "Other" },
  { text: "aquarium fish food flakes and water purifier drop", category: "Other" },
  { text: "dog collar harness anti flea tick shampoo", category: "Other" },
  { text: "house painting wall putty and paint brush touchup", category: "Other" },
  { text: "electrician switch board rewiring labour charge", category: "Other" },
  { text: "carpenter door latch hinges hinge oil repair", category: "Other" },
  { text: "glass window pane replacement crack repair", category: "Other" },
  { text: "garbage sweeper monthly waste collection tip", category: "Other" },
  { text: "blessing charity donation blind school welfare", category: "Other" },
  { text: "red cross disaster emergency relief contribution", category: "Other" },
  { text: "feed stray cows and birds seeds grain donation", category: "Other" },
  { text: "diwali festival gift hampers dry fruits for staff", category: "Other" },
  { text: "baby shower ceremony congratulations gift envelope", category: "Other" },
  { text: "housewarming puja havan priest dakshina offering", category: "Other" },
  { text: "funeral wreath flowers and condolences donation", category: "Other" },
  { text: "umbrella repair ribs replacement mechanic", category: "Other" },
  { text: "zipper runner replacement for travel bag luggage", category: "Other" },
  { text: "suit dry clean steam press blazers coats", category: "Other" },
  { text: "curtain dry cleaning and sofa upholstery shampoo", category: "Other" },
  { text: "delhivery courier parcel home pickup charges", category: "Other" },
  { text: "blue dart international document courier express", category: "Other" },
  { text: "india post registered post acknowledgment tracking", category: "Other" },
  { text: "document scanning and laminate certificate card", category: "Other" },
  { text: "pan card reprint and address correction nsdl fee", category: "Other" },
  { text: "aadhaar card biometric update enrollment charges", category: "Other" },
  { text: "voter id voter card duplicate pvc printout", category: "Other" },
  { text: "lost metro token replacement fee penalty", category: "Other" },
  { text: "wallet lost petty cash unaccounted adjustment", category: "Other" }
];
